# fly.toml app configuration file generated for billowing-snow-4429 on 2023-11-02T09:53:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-snow-4429"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
